### ISSUE TITLE
Enable builds via Travis CI

### ISSUE THREAD

**Issue by ebrelsford** [mhkeller/indian-ocean#13]
Now that we have some tests, maybe enable builds on [Travis CI](https://travis-ci.org/)? I added [a config file](https://github.com/mhkeller/indian-ocean/blob/master/.travis.yml) but only repo admins can enable builds.

**Comment by mhkeller** [comment]
Waiting on some authentication stuff and then shall add.

**Comment by mhkeller** [comment]
Done: https://github.com/mhkeller/indian-ocean/commit/0e872e564ad3304676f09bc41bc9a58f5f04c785
We should add an io.js test for travis and a badge

**Comment by ebrelsford** [comment]
Added io.js in 41c4ca72

**Comment by mhkeller** [comment]
I once saw a little iojs badge on someone's readme. I'll keep looking for that. You could look in the travis.yml to see but, for instance, having never used travis before, didn't know that and always thought "oh nice it works in both"

I stole these badges from someone elses readme, im finding not many resources on them tho

**Comment by ebrelsford** [comment]
I think people just make these up as they go. Could maybe use [node-project-badge](https://github.com/hmil/node-project-badge) to generate them?

**Comment by ebrelsford** [comment]
Oh or [shields.io](http://shields.io/)

**Comment by mhkeller** [comment]
Ah shields.io looks nice. plus, yknow, what's a trustworthy project without a .io domain?
