### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ebrelsford** [mhkeller/indian-ocean#14]
I'm considering using [documentationjs](http://documentation.js.org/) for documentation that will be a bit easier to navigate than the current docs. Here's an [example of what that would look like](http://ebrelsford.github.io/indian-ocean/docs/). Thoughts?

**Comment by mhkeller** [comment]
That's awesome. Do we add a gulp process to build it?

**Comment by ebrelsford** [comment]
Maybe. I'm still figuring that part out. Have you dealt with this kind of thing before? I'm more concerned with checking out `gh-pages` and syncing it than generating the docs, which is actually pretty easy.

**Comment by mhkeller** [comment]
Keeping it to

``` bash
npm run gen-docs (or whatever)
git checkout gh-pages
git merge master
git push origin gh-pages
```

seems fine for now. The downside is that the gh-pages site doesn't actually have an `index.html`.

**Comment by mhkeller** [comment]
Or if it can plop the `index.html` in the main folder and put the stylesheets and everything else in `docs` it seems that's a pattern https://github.com/jashkenas/underscore/tree/master

**Comment by ebrelsford** [comment]
Ah yeah, it would be easy enough to make `docs/index.html` be the root `index.html` for `gh-pages`, I was just avoiding that in case we wanted a more general index page. If we wanted to put it in the root I'd probably try using [git subtree](https://gist.github.com/cobyism/4730490).
