### ISSUE TITLE
Support for non utf-8?

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#17]
Currently most parsers use the `utf-8` flag as the second arg to `fs.readFile` as a way to convert it from a buffer to a string. I'm not sure how this will work across encodings. Perhaps doing `toString()` better preserves? Encodings are not my strong suite, however and I usually glean whatever wisdom I can from @aubergene, poke.

**Comment by aubergene** [comment]
The encoding is how characters are represented as bytes, `toString()` isn't really involved. UTF-8 is so ubiquitous now that if you encounter files in another encoding, then converting them should probably be the first step. Have you seen Rich's [sander](https://github.com/Rich-Harris/sander)?

**Comment by mhkeller** [comment]
Cool, I feel we can close this as outside the scope of the lib then. Thanks for the quick reply!

Rich and I have talked about sander, which is super cool. I think indian-ocean is more about data files as opposed to a super fs but certainly it does flirt with that line in functions like readdirInclude, which might be sander candidates. The promise-based structure is also a big difference.
