### ISSUE TITLE
Support geocsv

### ISSUE THREAD

**Issue by ebrelsford** [mhkeller/indian-ocean#18]
I've started work on this in a branch (5ac1a669). The idea is that we can detect lat/lng columns in delimited text files and return GeoJSON objects rather than plain old JSON objects. This should work fine for `psv` and `tsv`, too.

Thoughts? My goal is to be able to plop just about anything into `indian-ocean` and get something useful to import into [tablespoon-desktop](https://github.com/ebrelsford/tablespoon-desktop), so forcing GeoJSON here makes sense to me. But I understand if it's crossing a line for you.

**Comment by mhkeller** [comment]
I think adding it to `readCsv` is a little tricky since then there isn't a way to read in a csv that has lat/lng like column headers the normal way. It would make most sense to have a `readGeoCsv` function that attempts to read in the file and throws an error if it isn't valid geocsv. 

For `readData` it would use `readCsv` if the file ends in `.csv` and `readGeoCsv` if it ends in `.geocsv` or whatever the convention is.

That way if you want to explicitly load a csv as geojson you have a function for it and your csv loading can be normal as it is.

**Comment by ebrelsford** [comment]
Sure separate functions could potentially work. Or maybe add options to `readCsv` and `readData`. eg, if `allowGeoJson` is `true`, convert to GeoJSON, else read as JSON as usual.

There isn't a `.geocsv` extension convention, really, but people often do put geometry columns in `.csv` files.

**Comment by mhkeller** [comment]
ya i could definitely see the utility of a flag that directs `readCsv` into `readGeoCsv`, like if you wanted to have some switch in your code anticipating two different datatypes.

**Comment by mhkeller** [comment]
These switches to `readData` are similar to supporting flattening of `json` data in https://github.com/mhkeller/indian-ocean/issues/31. They're data-specific options to a function that can accept multiple data types. Doing it as different arguments runs into a lot of like `if arguments.length == 2` type stuff which can get hard to read and debug. perhaps we should move to passing-json-options pattern? What do you think @ebrelsford?

**Comment by ebrelsford** [comment]
I think passing options as an object would be better than extra arguments for the reasons you state, and it's a pretty standard way of doing this.

**Comment by mhkeller** [comment]
Ya I think this'll become a breaking change but a good idea.

**Comment by ebrelsford** [comment]
I should have time later this week to give it a look.

**Comment by mhkeller** [comment]
This config option would also work for specifying things like https://github.com/mhkeller/indian-ocean/issues/27

**Comment by mhkeller** [comment]
@ebrelsford are geocsvs still in use?

**Comment by mhkeller** [comment]
Gonna close for now. Will reopen if this seems like something we want to support.
