### ISSUE TITLE
`appendData` function?

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#19]
I have a use-case where I'd like to bake out a csv every time a scraper runs and also add data to an existing csv. I could also see cases where you might want to append to json. 

For csvs perhaps chopping off the header and delegating to `appendFile` would work. For Json, you'd have to chop off the closing `]` for that same strategy to work if you want to avoid parsing the json.

**Comment by mhkeller** [comment]
For now I might try an implementation where it reads the existing file in as json, appends to that array of objects and converts back to the out format. It's not super-performant but it's most consistent across data formats and can more easily handle appending to an empty file.

**Comment by ebrelsford** [comment]
Agreed, I think that solution is the least likely to break things, especially when we start looking at more complicated structures such as GeoJSON or DBF.

**Comment by mhkeller** [comment]
Needs tests. It uses `appendFile` and `appendFileSync` with an empty string to handle creating the file if it doesn't already exist. This seemed better than dealing with the deprecated `fs.exists` / `fs.access` fiasco.
