### ISSUE TITLE
How do we link back to GitHub from docs?

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#21]
@ebrelsford It would be good if we had a `position: fixed;` "Fork me on GitHub" ribbon in the docs. Or if the header linked back to the repo. It currently links to `mhkeller.github.io`, which is a blank page. I looked around the Documentation Js stuff but didn't see the right parameter.

**Comment by ebrelsford** [comment]
Hm yeah I haven't looked into that yet but agreed.

**Comment by mhkeller** [comment]
Okie doke. So now we're using a local theme courtesy of the new `-t` flag in documentationjs.
Added a ribbon! https://github.com/mhkeller/indian-ocean/commit/be4e73d1f8ac393499ba022f688a3e294c2b6d9a
