### ISSUE TITLE
Add more examples to documentation

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#22]
The documentation should have more usage examples.

**Comment by ebrelsford** [comment]
:+1:

**Comment by mhkeller** [comment]
Plus the intro text from the readme would be nice. It can be put into this div: https://github.com/mhkeller/indian-ocean/blob/master/docs/theme/index.hbs#L50

Just need to figure out what kind of classes it will have for styling purposes

**Comment by mhkeller** [comment]
Did most of the writers, but they're all the same so that was easy https://github.com/mhkeller/indian-ocean/commit/d90ce6a5313ab6550b4fce51351b4f54b09afd09

**Comment by mhkeller** [comment]
Everything should have an example now https://github.com/mhkeller/indian-ocean/commit/c420146e2076ba5e1b16b9d864db2f3283f0c018
