### ISSUE TITLE
Automate building docs with Travis

### ISSUE THREAD

**Issue by ebrelsford** [mhkeller/indian-ocean#24]
[This script](https://github.com/mhkeller/indian-ocean/blob/master/build/travis-docs.sh) mostly takes care of building the docs and pushing them to `gh-pages` every time we push to master. This is nice because I have forgotten to do it in the past.

The only issue is that we need to generate a [token](https://github.com/settings/tokens) that can write to the repo and add it to our [.travis.yml](https://github.com/mhkeller/indian-ocean/blob/master/.travis.yml) under `secure`. I've tried a few times and I don't think I have access to do this.

There are good instructions in [this blog post](http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/) under **how to do it**, steps 3 and 4 if you don't mind trying it at some point, @mhkeller. When you do, please delete the item under `secure` right now as it's my invalid token!

**Comment by mhkeller** [comment]
Will do. Nice how it encrypts the token so you can commit it. As long as travis doesn't get hacked.

**Comment by ebrelsford** [comment]
Yeah it's pretty smart.

**Comment by mhkeller** [comment]
Works? https://github.com/mhkeller/indian-ocean/commit/cc7ea462b66efd3b9e6e972b6c0892a43c1bc8f3

**Comment by ebrelsford** [comment]
Whoo! :+1:
