### ISSUE TITLE
Clean up looping commits?

### ISSUE THREAD

**Issue by ebrelsford** [mhkeller/indian-ocean#25]
I should have foreseen this, but committing to `master` in a script run whenever `master` is committed to led to a [lot of commits](https://github.com/mhkeller/indian-ocean/commits/master). :sob: 

Thoughts about rebasing? Since it's mostly you and me it shouldn't be super annoying to get back on track.

**Comment by mhkeller** [comment]
<3 this. i'll leave the rebasing magic up to you :). if left to my blunt devices i would checkout that last commit, add the stuff in new commits and force push.

**Comment by ebrelsford** [comment]
Ooookay, I think I did it without burning everything down. You'll want to do something like

```
git fetch origin
git reset --hard origin/master
```

to get back in sync with the repo. And be sure to move any changes you made after cc5873393 to a branch first.

**Comment by mhkeller** [comment]
Looks good!
