### ISSUE TITLE
exists/existsSync

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#26]
Deprecating `fs.exists` and `fs.existsSync` has causes a large brouhaha in iojs world: https://github.com/nodejs/io.js/issues/1592#issuecomment-98392899

I tend to use this function quite frequently for writing scrapers and things. It's useful to check if a file exists to see where you left off. It seems awkward to attempt to open the file in this situation since you have no intention of reading it, and doing that for a large number of files seems like you'd run out of memory, which is why you would write an incremental scraper in the first place.

So, some wrapper around `fs.access` would be nice. The issue is what API should the function have. 

`fs.existsSync` is fairly straightforward, it returns `true` or `false`.

`fs.exists` is weirder since [its API](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) returned `exists` as the callback, which goes against returning `err` as the first argument.

I've set it up currently to return `err` as first and `exists` as second. This is a bit redundant since they will always be opposites but it seems most legible. 

https://github.com/mhkeller/indian-ocean/blob/a2e3f415018f85e1c5abb3083fa3753d41b5b52b/lib/index.js#L81-L98

``` js
/**
 * Asynchronously test whether a file exists or not by using `fs.access` modified from https://github.com/nodejs/io.js/issues/1592#issuecomment-98392899.
 * @param {String} fileName the name of the file
 * @param {Function} callback has the signature `(err, exists)`
 *
 * @example
 * var exists = io.exists('path/to/data.tsv', function (err, exists) {
 *   console.log(err) // `false` if the file exists, `true` if not.
 *   console.log(exists) // `true` if the file exists, `false` if not.
 * })
 *
 */
helpers.exists = function (filename, cb) {
  fs.access(function (err) {
    var exists = err ? false : true
    cb(!exists, exists)
  })
}
```

What do you think @ebrelsford?

I'm getting a `standard` error when I test

```
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
lib/index.js:96:23: Unnecessary use of boolean literals in conditional expression
```

**Comment by ebrelsford** [comment]
Hm. Maybe the callback's first parameter should take whatever error `access` passed?

I think `standard` is complaining about the ternary operator where you could also say

``` javascript
var exists = typeof err !== 'undefined'
```

So how about:

``` javascript
helpers.exists = function (filename, cb) {
  fs.access(function (err) {
    cb(err, typeof err !== 'undefined)
  })
}
```

**Comment by mhkeller** [comment]
Ya that makes more sense. A quick test looks like `fs.access` returns `null` when err is falsey. something like this it's happy with. 

``` js
helpers.exists = function (filename, cb) {
  fs.access(function (err) {
    cb(err, err !== null)
  })
}
```
