### ISSUE TITLE
When writing out files, create intermediate dirctories if they don't exist, like `mkdir -p`

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#27]
Could be an argument or a config flag

**Comment by mhkeller** [comment]
Could use [node-fs](https://github.com/bpedro/node-fs) which has a pretty good implementation.

**Comment by mhkeller** [comment]
This looks better: https://www.npmjs.com/package/mkdirp

**Comment by ebrelsford** [comment]
I've used it and can confirm :+1:

**Comment by mhkeller** [comment]
is there any downside to making this the default behavior?

On Tue, Sep 15, 2015 at 12:40 AM, Eric Brelsford notifications@github.com
wrote:

> I've used it and can confirm [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mhkeller/indian-ocean/issues/27#issuecomment-140119079
> .

## 

@mhkeller
mhkeller.com

**Comment by ebrelsford** [comment]
Not sure! I feel like it's kind of a failsafe _not_ being the default, as with the `mkdir` command.

**Comment by mhkeller** [comment]
This has been implemented in 1.0.0. See [changelog](https://github.com/mhkeller/indian-ocean/blob/master/CHANGELOG.md#100) for details
