### ISSUE TITLE
Add descriptive error if data is not an array of objects format on write

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#3]
This is only the case when the output format is a dsv.

**Comment by mhkeller** [comment]
Some more info on this: If you try and write a nested json object to a csv, you'll get a dsv error. If you're not familiar with dsv, however, this error will be confusing. The lib should catch the error and return a better response such as "It appears you are trying to convert nested data into a two-dimensional format (csv, tsv, etc). Please flatten your objects first."

**Comment by ebrelsford** [comment]
Makes sense, could also offer an option to flatten for you if we wanted?

**Comment by mhkeller** [comment]
could be a lil too fancy. i guess the extreme fanciness would be if it recursively made your file format. it can be csvs all the way down

**Comment by mhkeller** [comment]
Or https://github.com/toddself/flatten-object

**Comment by mhkeller** [comment]
Descriptive error is supported in 0.7.0. I haven't implemented a flattening. @ebrelsford if you want to take a crack at implementing with a proposed usage by all means. I'm not sure where the easiest way to put that flag would be. Gonna make a new issue for it.
