### ISSUE TITLE
Handle multi-dimensional data

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#31]
Per https://github.com/mhkeller/indian-ocean/issues/3. This lib looks useful: https://github.com/toddself/flatten-object

It would be nice to be able to specify a custom flattening function so you could concatenate with certain strings or something. I'm not sure what the best usage is for this, however.

**Comment by mhkeller** [comment]
It could be good to also support the unflatten option within the `read` functions.

**Comment by mhkeller** [comment]
fyi lets work on this on the 1.1 branch.

**Comment by ebrelsford** [comment]
I'm open to it, but I'm not sure how useful it would be?

**Comment by mhkeller** [comment]
The utility would be if you wrote out a file into a flat format, you could then restore its non-flatness by reading it in.

**Comment by mhkeller** [comment]
hm maybe im not understanding this correctly. I thought this was a feature where you could create a csv from a multi-dimensional json object. the flatten has so far been implemented on the read functions though. My thinking was: 
- write fns -> flatten multidimensional data to csv
- read fns -> expand csv data to multidimensional json

**Comment by mhkeller** [comment]
@ebrelsford is this still a useful one do you think?

**Comment by ebrelsford** [comment]
Not sure, at this point I'm fine waiting until we have a clear use case for it.

**Comment by mhkeller** [comment]
Gonna close this one since neither of us has found a need.
