### ISSUE TITLE
Pass parser options

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#40]
[js-yaml](https://github.com/nodeca/js-yaml), which we use for yaml parsing has different security features. We currently use the `dump` method which is the most permissive. Now that options can easily be passed in to each function, we should allow for different loading and change the default to `safeLoad`, which is their recommended method.

**Comment by mhkeller** [comment]
Readers and writers should have an option such as `parserOptions`, which will be options that external libraries support such as what yaml `safeLoad` has. https://github.com/nodeca/js-yaml#safedump-object---options-

This could also use a convention such as `mode` that would specify different methods on these libraries, such as `safeDump` versus `dump`.

**Comment by brittharr** [comment]
:+1: for json pretty printing in particular

**Comment by mhkeller** [comment]
This should be implemented on the [`parse-options`](https://github.com/mhkeller/indian-ocean/tree/parse-options) branch.

Still need to 
- [x] do yaml settings
- [x] tests for parsing rows with dsvs

**Comment by mhkeller** [comment]
Very exciting news. This is now implemented on `v2.0.0` and docs should be updated accordingly
