### ISSUE TITLE
breakpoints are off on docs

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#42]
the css in the docs needs to be fixed to account for some weird breakpoint behavior

**Comment by ebrelsford** [comment]
Hm it looks okay on my end?

**Comment by mhkeller** [comment]
Between 1024px and 640px it looks like this in FF, Chrome and Safari
<img width="932" alt="screen shot 2015-12-08 at 11 22 40 pm" src="https://cloud.githubusercontent.com/assets/498744/11676642/5a0148ca-9e02-11e5-91cf-cf452670e845.png">

**Comment by mhkeller** [comment]
Fixed in 1.1
