### ISSUE TITLE
Remove extraneous `read` functions

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#44]
Now that `readData` and `readDataSync` can be passed formats to explicitly read, there's no need for `readCsv` and all those things. They should be removed, I feel. Any objections?

**Comment by ebrelsford** [comment]
Yes! Either way the read and write functions should be symmetric.

**Comment by mhkeller** [comment]
To make the docs easier to read, i've put these under `shorthandReaders` and added some info saying that they are simply using `readData` with specific parsers.
