### ISSUE TITLE
Write DBF File

### ISSUE THREAD

**Issue by evallgar** [mhkeller/indian-ocean#45]
I have a file called CONFIG.DBF  There are two things I need to do with this file:

1- Get the value of a field that contains a number (latest order number)
2- Increment this value +1

There are some other .dbf files that I need to read / write. Reading was not a problem, writing is where I'm sure I'm missing something.

Any help is really appreciated.

Thanks!

**Comment by mhkeller** [comment]
Hi, What is the error you are running into? This library can help you with reading and writing the dbf data into json. 

After reading in the data, what you've described in steps 1 and 2 you would handle on your own in JavaScript. Once you've manipulated the data how you like, you would then write out the dbf with indian-ocean using the `writeData` function http://mhkeller.github.io/indian-ocean/docs/#writers/writedata. Let me know if that function is not working properly.

**Comment by mhkeller** [comment]
Closing since this seems to be unrelated to this library. Reopen if you're running into an issue.
