### ISSUE TITLE
Add some simple support for txt files

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#5]
Read a file in with the `utf-8` flag with `fs.readFile` if it's extension is `.txt`.

Add support to write out as well.

**Comment by ebrelsford** [comment]
What does it mean to read a txt file as json? What would the structure be, an array of lines?

**Comment by mhkeller** [comment]
This feature I was just thinking as a simple way to read in a file as utf-8, essentially `fs.readFile(path, 'utf-8', cb)`. Same as calling `toString()` without passing in the `utf-8` flag.

If you were to read in a json file as text then you would manually `JSON.parse`. We could add support for `.jsonlines` files though, which is more of what you're getting at.

**Comment by ebrelsford** [comment]
Ah I see. That could also potentially be the fallback if we can't figure out what type of file you are passing?

**Comment by mhkeller** [comment]
Ya good idea!

**Comment by mhkeller** [comment]
This is supported in 0.7.0!
