### ISSUE TITLE
Allow option to strip comments from json

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#51]
Use https://www.npmjs.com/package/strip-json-comments

The idea is that it's nice to put comments in `config.json` objects and things.

**Comment by mhkeller** [comment]
If yr interested in a quicker one than geocsv @akanik

**Comment by aubergene** [comment]
I don't like this idea as it isn't valid JSON as therefore encourages the production of non-valid JSON. If you want to use comments, then use YAML or similar

**Comment by mhkeller** [comment]
@aubergene seems reasonable and there's been no pressing need for this since the issue was created. closing...
