### ISSUE TITLE
Read an xlsx file with multiple sheets

### ISSUE THREAD

**Issue by JSDiamond** [mhkeller/indian-ocean#56]
Return an array with each sheet as a json object. 
Would be nice to keep the sheet name in there as well. 
Gook package to use https://www.npmjs.com/package/xlsx

**Comment by mhkeller** [comment]
Hmm so this is a bit tricky. Other parsers, with the exception of dbf readers, read in the file in using `fs.readFile` as `utf-8` and then parsing the string in the appropriate format. xlsx has its own file reader, though, so it would have to come upstream of `fs.readFile`. That would make it kind of complicated. Or maybe a more generic solution would be to group parsers as those that use `fs.readFile` versus those that bring their own file reader. 

Another usage would be to have a separate function that's `io.readXls(path, 'sheet-name')`.

It would be nice to roll `dbf` into `io.reaData` so maybe the first option is a better solution.

**Comment by mhkeller** [comment]
This should also come with a writer since xlsx has that ability I believe

**Comment by mhkeller** [comment]
@JSDiamond As of 3.0.0, there's a [concept of loaders](https://github.com/mhkeller/indian-ocean/blob/ef9702c6a7e3121956718c1971453835e20c7067/src/loaders/index.js) which handles the above-mentioned `fs.readFile` stuff so this should be implementable.

What should the API be like? Should it try to standardize it so that you always get back the `workbook.Sheets` object and can then access a specific sheet by name? Or just give you back the workbook?

Either way, loading it in via the streaming API seems fine

```js
var fs = require('fs');
var XLSX = require('xlsx');
function process_RS(stream/*:ReadStream*/, cb/*:(wb:Workbook)=>void*/)/*:void*/{
  var buffers = [];
  stream.on('data', function(data) { buffers.push(data); });
  stream.on('end', function() {
    var buffer = Buffer.concat(buffers);
    var workbook = XLSX.read(buffer, {type:"buffer"});

    /* DO SOMETHING WITH workbook IN THE CALLBACK */
    cb(workbook);
    // OR
    cb(workbook.Sheets)
  });
}
```

**Comment by aubergene** [comment]
`readFile` just wraps `read` so it could be used in a similar way to other parsers.

https://github.com/SheetJS/js-xlsx/tree/master/demos/server

**Comment by mhkeller** [comment]
Cool that’s a bit simpler. 

Two usage options:
1. It returns an array of arrays. It’s similar to things like `io.readdirFilterSync(‘dir’).map(io.readDataSync)`. The array could have an object on it that’s a lookup and/or each child array has its sheet name as a property on the array. 
2. It returns the lookup object with each sheet as a value. 

Whatever the default is, the behavior should be configurable via `options`. There should also be an option to `include` and `exclude` certain sheets by name or regular expression similar to `io.readdir` functions.

**Comment by JSDiamond** [comment]
Aside: If there's a special function for xlsx, like ` io.readXls(path, 'sheet-name')`, maybe it can have an ignore or include argument as glob or regex, rather than just a 'sheet name'. Then you can include only sheets that start with an underscore, etc.  
@aubergene If this ends up in the cave, can we have a that include argument passed in by spelunk?

**Comment by aubergene** [comment]
I think I prefer the 1st option, so something like this? I just checked if Excel would allow multiple sheets with the same name, and it didn't for me at least :)

```js
var tmp = wb.SheetNames.map(d => XLSX.utils.sheet_to_json(wb.Sheets[d]))
tmp.SheetNames = wb.SheetNames
```

@JSDiamond Spelunk already has an [exclude](https://github.com/Rich-Harris/spelunk#optionsexclude) option, which we could expose and document, but in general I'd encourage people just to not put the file in the cave in the first place.

**Comment by JSDiamond** [comment]
@aubergene it would be to include only specific sheets within a file, not a whole file

**Comment by mhkeller** [comment]
I put this together yesterday. It optionally returns either

1. An array of arrays with each array getting a `name` property
2. A lookup object of `name` -> `array`

Need to implement the filter functions on sheet name

```js
var fs = require('fs')
var XLSX = require('xlsx')
var _ = require('underscore')

var defaults = {
  format: 'list'
}

module.exports = function readXlsxSync (filePath, _opts) {
  var buf = fs.readFileSync(filePath)
  var wb = XLSX.read(buf, {type: 'buffer'})
  _opts = _.defaults(_opts || {}, defaults)

  var sheetNames = filter(wb.SheetNames, _opts)

  if (_opts.format === 'list') {
    return sheetNames.map(d => {
      var jsonSheet = XLSX.utils.sheet_to_json(wb.Sheets[d])
      jsonSheet.name = d
      return jsonSheet
    })
  } else if (_opts.format === 'object') {
    let lookup = {}
    sheetNames.forEach(d => {
      lookup[d] = XLSX.utils.sheet_to_json(wb.Sheets[d])
    })
    return lookup
  } else {
    throw new Error('options.format must be either "list" or "object"')
  }
}

function filter (sheetNames, _opts) {
  if (_opts.include) {
    // TK, sheetNames = filteredList
  }
  if (_opts.exclude) {
    // TK, sheetNames = filteredList
  }
  return sheetNames
}

```

**Comment by rdmurphy** [comment]
Sorry to randomly zombie this issue, but just wanted to note that this functionality is present in [`copytext`](https://github.com/rdmurphy/node-copytext) right down to the ability to include/exclude sheets!

**Comment by mhkeller** [comment]
@rdmurphy cool! I just used `copytext` today and worked great. copytext always returns an object right? I'm wondering if that should be the default behavior for this or to maintain consistency between other readData functions it should default to an array. Thoughts? @aubergene @JSDiamond

**Comment by mhkeller** [comment]
I think always returning an array is the way to go. Will need to look back into the object returned.

**Comment by mhkeller** [comment]
Altho that's not the case for yaml, hmmm.

**Comment by mhkeller** [comment]
As of 4.0.0 yaml is no longer supported.

**Comment by mhkeller** [comment]
I'm closing this since it seems other libraries are better able to read in xlsx files and since the format will not be consistent with other file formats (array of row objects vs array of sheet arrays), it's a bit too complex.
