### ISSUE TITLE
Allow files to be an array

### ISSUE THREAD

**Issue by aubergene** [mhkeller/indian-ocean#58]
So that you do things like this

```js
var json_data = io.readDataSync([__dirname, 'path', 'to', 'data.csv'])
```

**Comment by mhkeller** [comment]
I could see this being useful for making it easier to do cross-os-compatible file paths. Is that the use case you were thinking?

**Comment by aubergene** [comment]
Yes, and just mainly for convenience since indian-ocean already pulls in path so it's one less require and a bit shorter to write.

**Comment by mhkeller** [comment]
@aubergene wanna take a crack at it? If you could also add it to the `rollup` branch that would be useful. I need to figure out how documentation generation works now that it's broken up into files but that branch is close to ready to merge.

**Comment by mhkeller** [comment]
@aubergene are you still thinking this is a good idea? I remember a conversation where you thought we wouldn't want to do this anymore.

**Comment by aubergene** [comment]
yeah, I think it's tricky to fit it in. I started on the io-lite idea but didn't get further
