### ISSUE TITLE
write an empty array to a json file logs an incorrect warning

### ISSUE THREAD

**Issue by 1wheel** [mhkeller/indian-ocean#77]
`io.writeDataSync('test.json', [])`

```
[indian-ocean] Warning: You didn't pass any data to write for file: `test.json`. Writing out an empty file...
```

`test.json` is written out correctly:

```
[]
```

**Comment by mhkeller** [comment]
Do you think it should say `"Writing out an empty array"` or that it shouldn't' issue a warning in this scenario? I've found it useful to know if my length is zero sometimes so I would probably lean toward changing it to being accurate that it's writing a zero-length array but curious to hear other ideas! 

I'm not sure if adding some logging level would make sense...

**Comment by 1wheel** [comment]
It was cluttering up papertrail logs; in this case I did want `[]` to be written. 

Maybe a `muteWarnings` option?

**Comment by mhkeller** [comment]
Should it be a global setting like `io.settings({muteWarnings: true})`, on the call level `io.writeDataSync(filePath, [], {muteWarnings: true})` or BOTH?

**Comment by mhkeller** [comment]
I can do on the call for now. Maybe something like `{verbose: <Boolean>}`

**Comment by 1wheel** [comment]
call seems good!

**Comment by mhkeller** [comment]
`verbose: false` is now an option in `writeData` and `writeDataSync`: https://github.com/mhkeller/indian-ocean/blob/master/CHANGELOG.md#310
