### ISSUE TITLE
Get rid of `detailed: true` option on readdirFilter functions

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/indian-ocean#79]
I have never ended up using this. If I need the filename I do `const fileName = path.basename(fullPath)`. This option adds a lot of complexity and has been holding up implementing https://github.com/mhkeller/indian-ocean/issues/71 because of how to handle the multiple object types.

This was a recent edition and kinda in the weeks so I'm not sure if anyone is actually using this option. If there are no objections @aubergene @1wheel I will remove and add the recursive option, which is much more useful.

**Comment by 1wheel** [comment]
I didn't know there was a `detailed` option! Won't miss it.
