### ISSUE TITLE
CSV parser doesn't strip BOM

### ISSUE THREAD

**Issue by aubergene** [mhkeller/indian-ocean#80]
This is the expected behaviour of [d3-dsv](https://github.com/d3/d3-dsv#byte-order-marks) however it isn't necessarily what a user would expect as the header string appears valid but contains invisible BOM characters.

**Comment by aubergene** [comment]
[bom.csv.zip](https://github.com/mhkeller/indian-ocean/files/3509432/bom.csv.zip)

Attached example with BOM (zipped due to Github restrictions on .csv file type)

**Comment by mhkeller** [comment]
How would you think [strip-bom](https://www.npmjs.com/package/strip-bom) should be implemented?

**Comment by mhkeller** [comment]
Would it be as simple as after `fs.readFile` but before it parses it, you strip-bom? Will it always and only be the leading character or are you seeing it elsewhere in the header row?

**Comment by mhkeller** [comment]
Using [this](https://github.com/sindresorhus/strip-bom/blob/d5696fdc9eeb6cc8d97e390cf1de7558f74debd5/index.js#L3) as the function, would applying that to the data string do it @aubergene?
